<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mail_helper' shared service.

include_once $this->targetDirs[3].'/src/Service/MailHelper.php';

return $this->services['mail_helper'] = new \App\Service\MailHelper($this->getEnv('MAILER_NO_REPLY'), ($this->services['mailgun.swift_transport.transport'] ?? $this->load('getMailgun_SwiftTransport_TransportService.php')), ($this->services['twig'] ?? $this->getTwigService()), $this, ($this->services['user_manager_service'] ?? $this->load('getUserManagerServiceService.php')), ($this->services['doctrine.orm.default_entity_manager'] ?? $this->load('getDoctrine_Orm_DefaultEntityManagerService.php')));
