<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'git.handler' shared service.

include_once $this->targetDirs[3].'/src/Service/GitHandler.php';

return $this->services['git.handler'] = new \App\Service\GitHandler($this->getEnv('GIT_BRANCH'), $this->getEnv('APP_SECRET'), $this->getEnv('GIT_GITGUB_SECRET'), $this->getEnv('GIT_DOCTRINE_UPDATE'));
