<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'open_tok' shared service.

include_once $this->targetDirs[3].'/src/Service/OpenTokHelper.php';

return $this->services['open_tok'] = new \App\Service\OpenTokHelper($this->getEnv('OPENTOK_KEY'), $this->getEnv('OPENTOK_SECRET'));
