<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'fungio.google_calendar' shared service.

include_once $this->targetDirs[3].'/vendor/fungio/google-calendar-bundle/Fungio/GoogleCalendarBundle/Service/GoogleCalendar.php';

return $this->services['fungio.google_calendar'] = new \Fungio\GoogleCalendarBundle\Service\GoogleCalendar();
