<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mailgun.swift_transport.transport' shared service.

include_once $this->targetDirs[3].'/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport.php';
include_once $this->targetDirs[3].'/vendor/cspoo/swiftmailer-mailgun-bundle/Service/MailgunTransport.php';
include_once $this->targetDirs[3].'/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Events/EventDispatcher.php';
include_once $this->targetDirs[3].'/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Events/SimpleEventDispatcher.php';
include_once $this->targetDirs[3].'/vendor/mailgun/mailgun-php/src/Mailgun/Mailgun.php';
include_once $this->targetDirs[3].'/vendor/mailgun/mailgun-php/src/Mailgun/HttpClientConfigurator.php';

$a = new \Mailgun\HttpClientConfigurator();
$a->setApiKey($this->getEnv('MAILGUN_API_KEY'));
$a->setHttpClient(($this->services['httplug.client'] ?? $this->load('getHttplug_ClientService.php')));

return $this->services['mailgun.swift_transport.transport'] = new \cspoo\Swiftmailer\MailgunBundle\Service\MailgunTransport(new \Swift_Events_SimpleEventDispatcher(), \Mailgun\Mailgun::configure($a), $this->getEnv('MAILGUN_DOMAIN'));
