# See https://symfony.com/doc/current/email/dev_environment.html
swiftmailer:
  transport: 'mailgun'
  # transport:        smtp
  # host:             127.0.0.1
  # port:             1025
  # stream_options:
  #   ssl:
  #     allow_self_signed: true
  #     verify_peer: false
  #     verify_peer_name: false