<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class UserPayments extends \App\Entity\UserPayments implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\UserPayments' . "\0" . 'id', '' . "\0" . 'App\\Entity\\UserPayments' . "\0" . 'user', '' . "\0" . 'App\\Entity\\UserPayments' . "\0" . 'userWorkshop', '' . "\0" . 'App\\Entity\\UserPayments' . "\0" . 'status', '' . "\0" . 'App\\Entity\\UserPayments' . "\0" . 'mollieId', '' . "\0" . 'App\\Entity\\UserPayments' . "\0" . 'amount', '' . "\0" . 'App\\Entity\\UserPayments' . "\0" . 'paymentUrl', '' . "\0" . 'App\\Entity\\UserPayments' . "\0" . 'paid', '' . "\0" . 'App\\Entity\\UserPayments' . "\0" . 'activeTill', '' . "\0" . 'App\\Entity\\UserPayments' . "\0" . 'created', '' . "\0" . 'App\\Entity\\UserPayments' . "\0" . 'updated'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\UserPayments' . "\0" . 'id', '' . "\0" . 'App\\Entity\\UserPayments' . "\0" . 'user', '' . "\0" . 'App\\Entity\\UserPayments' . "\0" . 'userWorkshop', '' . "\0" . 'App\\Entity\\UserPayments' . "\0" . 'status', '' . "\0" . 'App\\Entity\\UserPayments' . "\0" . 'mollieId', '' . "\0" . 'App\\Entity\\UserPayments' . "\0" . 'amount', '' . "\0" . 'App\\Entity\\UserPayments' . "\0" . 'paymentUrl', '' . "\0" . 'App\\Entity\\UserPayments' . "\0" . 'paid', '' . "\0" . 'App\\Entity\\UserPayments' . "\0" . 'activeTill', '' . "\0" . 'App\\Entity\\UserPayments' . "\0" . 'created', '' . "\0" . 'App\\Entity\\UserPayments' . "\0" . 'updated'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (UserPayments $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', []);

        return parent::getUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setUser($user)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', [$user]);

        return parent::setUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', []);

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', [$status]);

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getMollieId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMollieId', []);

        return parent::getMollieId();
    }

    /**
     * {@inheritDoc}
     */
    public function setMollieId($mollieId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMollieId', [$mollieId]);

        return parent::setMollieId($mollieId);
    }

    /**
     * {@inheritDoc}
     */
    public function getAmount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAmount', []);

        return parent::getAmount();
    }

    /**
     * {@inheritDoc}
     */
    public function setAmount($amount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAmount', [$amount]);

        return parent::setAmount($amount);
    }

    /**
     * {@inheritDoc}
     */
    public function getPaid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaid', []);

        return parent::getPaid();
    }

    /**
     * {@inheritDoc}
     */
    public function setPaid($paid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPaid', [$paid]);

        return parent::setPaid($paid);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreated', []);

        return parent::getCreated();
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdated', []);

        return parent::getUpdated();
    }

    /**
     * {@inheritDoc}
     */
    public function getActiveTill()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActiveTill', []);

        return parent::getActiveTill();
    }

    /**
     * {@inheritDoc}
     */
    public function setActiveTill($activeTill)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActiveTill', [$activeTill]);

        return parent::setActiveTill($activeTill);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserWorkshop()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserWorkshop', []);

        return parent::getUserWorkshop();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserWorkshop($userWorkshop)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserWorkshop', [$userWorkshop]);

        return parent::setUserWorkshop($userWorkshop);
    }

    /**
     * {@inheritDoc}
     */
    public function getPaymentUrl()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaymentUrl', []);

        return parent::getPaymentUrl();
    }

    /**
     * {@inheritDoc}
     */
    public function setPaymentUrl($paymentUrl): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPaymentUrl', [$paymentUrl]);

        parent::setPaymentUrl($paymentUrl);
    }

}
