<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJkBihxY\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJkBihxY/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJkBihxY.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJkBihxY\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerJkBihxY\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'JkBihxY',
    'container.build_id' => '4e60845e',
    'container.build_time' => 1627638958,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJkBihxY');
