security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

        in_memory:
            memory: ~

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        admin_area:
            pattern:    ^/admin/
            anonymous:  ~
            form_login:
                provider:   fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                default_target_path: admin_index
                login_path: admin_login
                check_path: admin_login_check
                remember_me: true
            logout:
                path:   admin_logout
                target: index

        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                default_target_path: account_index
                login_path: account_login
                check_path: account_login_check
                remember_me: true
                use_referer: true
            logout:
                path:   account_logout
                target: index

            remember_me:
                secret: '%env(APP_SECRET)%'

            anonymous:    true


    access_control:
        - { path: ^/admin/inloggen$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/registreren, role: ROLE_ADMIN }
        - { path: ^/admin/reset, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }

        - { path: ^/account/inloggen, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/account/registreren, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/account/reset, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/account/, role: ROLE_USER }