admin_collector_index:
    path:     /
    defaults: { _controller: App\Controller\Admin\CollectorController::index }

admin_collector_edit:
    path:     /nieuw-bewerken/
    defaults: { _controller: App\Controller\Admin\CollectorController::edit }
